# Generated by Django 3.2.4 on 2021-07-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_man',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_woman',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Erkek'), ('Female', 'Kadin')], max_length=100, null=True),
        ),
    ]
