# Generated by Django 3.2.4 on 2021-07-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadin')], max_length=100, null=True),
        ),
    ]
