# Generated by Django 3.2.4 on 2021-08-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210802_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='klasikpp.jpg', null=True, upload_to=''),
        ),
    ]
