# Generated by Django 3.2.4 on 2021-08-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='adress',
            field=models.CharField(blank=True, default='Adres Belirtilmedi', max_length=300, null=True, verbose_name='Adres'),
        ),
    ]
