# Generated by Django 3.2.4 on 2021-08-10 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_alter_post_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='yazar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='yazar'),
            preserve_default=False,
        ),
    ]
